version: '3.8'

services:
  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    restart: always
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - PORT=${PORT}
    ports:
      - "3001:3001"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:80"
    environment:
      - VITE_APP_API_URL=${VITE_APP_API_URL}
    depends_on:
      - backend